name: masamune_test
description: >-
  Masamune framework testing plugin.
  Basically, it is used inside Masamune framework.
version: 0.5.0
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune_test

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  sprintf: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
